version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - db
    environment:
      PORT: 5000
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: myapp_test
      DB_PORT: 3306
      DB_HOST: db
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_test
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
