version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - ./node_modules:/code/node_modules
    links:
      - db
    environment:
      PORT: 5000
      DB_USER: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      APP_SECRET: "!super_secret_code!"
      CREATE_SAMPLE_DATA_ON_STARTUP: 1
      RESET_DB_ON_STARTUP: 1
      NODE_ENV: "development"
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: food_timetable_dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: pass
